In [39]:
gamma_b_nom = 22 #kN/m3
gamma_b_cv = 10/100 
gamma_b_std = gamma_b_cv * gamma_b_nom #kN/m3

In [75]:
gamma_b = []

no_samples = list(range(1,4))
print(no_samples)

[1, 2, 3]


In [76]:
# gamma_b = gamma_b_nom + no_samples[0] * gamma_b_std
gamma_b

[]

In [77]:
for i in range(1,4):
    print(list(range(1,4)))


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [78]:
no_samples[0]

1

In [79]:
no_samples[1]

2

In [80]:
no_samples[2]

3

In [81]:
for i in range(0,3):
    print(no_samples[i])

1
2
3


In [88]:
gamma_b = []

for i in range(0,3):
    gamma_b = gamma_b_nom + no_samples[i] * gamma_b_std

gamma_b

28.6

In [119]:
import numpy as np

In [120]:
no_samples = list(range(1,4))
print(no_samples)

[1, 2, 3]


In [127]:
ones_array = np.ones((len(no_samples)), dtype = int)
print(ones_array)

[1 1 1]


In [136]:
gamma_b_nom = 22 #kN/m3

gamma_b_nom = np.array([gamma_b_nom * ones_array]) #to understand this step, look at https://www.delftstack.com/howto/numpy/numpy-transpose-a-1d-array/
print(gamma_b_nom.shape)

(1, 3)
[[22 22 22]]


In [139]:
gamma_b_nom = gamma_b_nom.T
print(gamma_b_nom)

[[22]
 [22]
 [22]]


In [140]:
print(gamma_b_nom + gamma_b_nom)

[[44]
 [44]
 [44]]


In [141]:
gamma_b_std = np.array([gamma_b_std * ones_array])
print(gamma_b_std)

[[2.2 2.2 2.2]]


In [142]:
gamma_b_std = gamma_b_std.T
print(gamma_b_std)

[[2.2]
 [2.2]
 [2.2]]


In [181]:
gamma_b = []

for i in range(0,len(no_samples)):
    gamma_b = (gamma_b_nom[i] + range(0,len(no_samples)) * gamma_b_std[i])

print(gamma_b)

[22.  24.2 26.4]


In [190]:
gamma_b = np.array([gamma_b]).T

In [191]:
float_formatter = "{:.1f}".format
np.set_printoptions(formatter = {'float_kind': float_formatter}) #for more info, look at https://stackoverflow.com/questions/68428028/how-can-0-decimals-be-included-when-working-with-numpy-floats

In [192]:
print(gamma_b)

[[[[[22.0]]

   [[24.2]]

   [[26.4]]]]]
