In [39]:
gamma_b_nom = 22 #kN/m3
gamma_b_cv = 10/100 
gamma_b_std = gamma_b_cv * gamma_b_nom #kN/m3

In [75]:
gamma_b = []

no_samples = list(range(1,4))
print(no_samples)

[1, 2, 3]


In [76]:
# gamma_b = gamma_b_nom + no_samples[0] * gamma_b_std
gamma_b

[]

In [77]:
for i in range(1,4):
    print(list(range(1,4)))


[1, 2, 3]
[1, 2, 3]
[1, 2, 3]


In [78]:
no_samples[0]

1

In [79]:
no_samples[1]

2

In [80]:
no_samples[2]

3

In [81]:
for i in range(0,3):
    print(no_samples[i])

1
2
3


In [88]:
gamma_b = []

for i in range(0,3):
    gamma_b = gamma_b_nom + no_samples[i] * gamma_b_std

gamma_b

28.6

In [119]:
import numpy as np

In [120]:
no_samples = list(range(1,4))
print(no_samples)

[1, 2, 3]


In [127]:
ones_array = np.ones((len(no_samples)), dtype = int)
print(ones_array)

[1 1 1]


In [136]:
gamma_b_nom = 22 #kN/m3

gamma_b_nom = np.array([gamma_b_nom * ones_array]) #to understand this step, look at https://www.delftstack.com/howto/numpy/numpy-transpose-a-1d-array/
print(gamma_b_nom.shape)

(1, 3)
[[22 22 22]]


In [139]:
gamma_b_nom = gamma_b_nom.T
print(gamma_b_nom)

[[22]
 [22]
 [22]]


In [140]:
print(gamma_b_nom + gamma_b_nom)

[[44]
 [44]
 [44]]


In [141]:
gamma_b_std = np.array([gamma_b_std * ones_array])
print(gamma_b_std)

[[2.2 2.2 2.2]]


In [142]:
gamma_b_std = gamma_b_std.T
print(gamma_b_std)

[[2.2]
 [2.2]
 [2.2]]


In [181]:
gamma_b = []

for i in range(0,len(no_samples)):
    gamma_b = (gamma_b_nom[i] + range(0,len(no_samples)) * gamma_b_std[i])

print(gamma_b)

[22.  24.2 26.4]


In [190]:
gamma_b = np.array([gamma_b]).T

In [191]:
float_formatter = "{:.1f}".format
np.set_printoptions(formatter = {'float_kind': float_formatter}) #for more info, look at https://stackoverflow.com/questions/68428028/how-can-0-decimals-be-included-when-working-with-numpy-floats

In [192]:
print(gamma_b)

[[[[[22.0]]

   [[24.2]]

   [[26.4]]]]]


In [193]:
import math #math documentation at https://docs.python.org/3/library/math.html
pi = math.pi

In [194]:
L = round(9260/1000, 3) #m
r_i = round(3450/1000, 3) #m
t = round(500/1000, 3) #m
r_e = round(3950/1000, 3) #m
r = round(1/2*(r_i + r_e), 3) #m

print(f'{r_i:.2f}', f'{r_e:.2f}', f'{r:.2f}') #round decimals example at https://kodify.net/python/math/round-decimals/

3.45 3.95 3.70


In [195]:
# gamma_b = 22 #kN/m3
fm_b = 8 #MPa

In [196]:
b = 1 #m -investigated arch barrel slice-

In [197]:
A_e = (1/4)*(pi * math.pow(r_e, 2)) #m2
print(A_e)

A_i = (1/4)*(pi * math.pow(r_i, 2)) #m2
print(A_i)

A = (A_e-A_i)
print(A)

12.254174844408688
9.348201639838129
2.905973204570559


In [200]:
P = gamma_b * A * b #a vector of P is expected, with length equal to gamma_b's length
print(P)

[[[[[63.9]]

   [[70.3]]

   [[76.7]]]]]


In [201]:
xp_re = 1/2 * L - (4/(3*pi)*r_e) #m
print(f'{xp_re:.2f}')

xp_ri = 1/2 * L - (4/(3*pi)*r_i) #m
print(f'{xp_ri:.2f}')

xp = ((xp_re*A_e)-(xp_ri*A_i))/A #m
print(f'{xp:.2f}')

2.95
3.17
2.27


In [204]:
H_a = (xp * P)/(2/3*t + r_i) #kN

V_a = P #kN

#S_a = math.sqrt(math.pow(H_a, 2) + math.pow(V_a, 2)) #kN -the math function doesn't work on array's elements- for more, look at https://stackoverflow.com/questions/63515866/only-size-1-arrays-can-be-converted-to-python-scalars


In [206]:
def myPow(H_a, V_a):
    S_a = math.sqrt(math.pow(H_a, 2) + math.pow(V_a, 2))
    return S_a

In [207]:
myPowVec = np.vectorize(myPow, excluded=['H_a', 'V_a'])

In [209]:
S_a = myPowVec(H_a, V_a)
print(S_a)

[[[[[74.6]]

   [[82.0]]

   [[89.5]]]]]


In [210]:
gamma_fL = 1.15
gamma_f_three = 1.0
e = t/6 #m
CF = 1
delta = 0.85
K = 0.50
alfa = 0.7
beta = 0.3
f_m = 4 #MPa

In [211]:
f_b = CF * delta * fm_b #MPa
f_k = K * math.pow(f_b, alfa) * math.pow(f_m, beta) #MPa
f_k

2.8996410582174934

In [212]:
R_d = 0.4 * b * f_k * (t-2*e)*1000 #kN
print(f'{R_d:.2f}')

386.62


In [214]:
E_d = gamma_fL * gamma_f_three * S_a #kN
print(E_d)

[[[[[85.7]]

   [[94.3]]

   [[102.9]]]]]


In [215]:
E_d <= R_d

array([[[[[ True]],

         [[ True]],

         [[ True]]]]])