In [64]:
import pandas as pd

In [65]:
Ed_arch_no_scour = pd.read_csv("demand.csv") #for the no scour case #for more, https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html
cols = [1] #for more, https://stackoverflow.com/questions/48641632/extracting-specific-columns-from-pandas-dataframe

Ed_arch_no_scour = Ed_arch_no_scour[Ed_arch_no_scour.columns[cols]]
Ed_arch_no_scour = Ed_arch_no_scour.values #for more, https://stackoverflow.com/questions/44238796/convert-pandas-series-into-numpy-array
type(Ed_arch_no_scour)
Ed_arch_no_scour[0:5]

array([[238.10061688],
       [194.94657029],
       [245.02036918],
       [238.05928344],
       [237.13694604]])

In [66]:
Rd_arch_no_scour = pd.read_csv("capacity.csv") #for the no scour case
Rd_arch_no_scour = Rd_arch_no_scour[Rd_arch_no_scour.columns[cols]]
Rd_arch_no_scour = Rd_arch_no_scour.values #for more, https://stackoverflow.com/questions/44238796/convert-pandas-series-into-numpy-array
type(Rd_arch_no_scour)
Rd_arch_no_scour[0:5]

array([[376.67048419],
       [273.42175287],
       [393.22642047],
       [376.57159136],
       [374.36484198]])

In [67]:
Fi = 0.9
Ed_arch_scour = Ed_arch_no_scour/Fi #for the scour case
Ed_arch_scour[0:5]

array([[264.55624098],
       [216.60730032],
       [272.24485464],
       [264.51031493],
       [263.4854956 ]])

In [68]:
Fc = 0.173
fi = 0.4
Rd_arch_scour = (Rd_arch_no_scour/fi) * Fc #for the scour case
Rd_arch_scour[0:5]

array([[162.90998441],
       [118.25490812],
       [170.07042685],
       [162.86721326],
       [161.91279416]])

In [69]:
safety_margin_no_scour = Rd_arch_no_scour - Ed_arch_no_scour
safety_margin_no_scour[0:5]

array([[138.56986731],
       [ 78.47518259],
       [148.20605129],
       [138.51230793],
       [137.22789594]])

In [70]:
safety_margin_scour = Rd_arch_scour - Ed_arch_scour
safety_margin_scour[0:5]

array([[-101.64625657],
       [ -98.3523922 ],
       [-102.17442779],
       [-101.64310167],
       [-101.57270145]])

In [71]:
pd.DataFrame(safety_margin_no_scour).to_csv("safety_margin_no_scour_arch.csv")
pd.DataFrame(safety_margin_scour).to_csv("safety_margin_scour_arch.csv")


In [72]:
failure_cases_no_scour = [safety_margin_no_scour <=0]
failure_cases_no_scour[0:5]

[array([[False],
        [False],
        [False],
        ...,
        [False],
        [False],
        [False]])]

In [73]:
import numpy as np

In [74]:
failure_cases_no_scour_number = np.count_nonzero(failure_cases_no_scour) #for more, https://thispointer.com/count-number-of-true-elements-in-a-numpy-array-in-python/#1
print(failure_cases_no_scour_number)

0


In [75]:
failure_cases_scour = safety_margin_scour <=0
failure_cases_scour[0:5]

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

In [76]:
failure_cases_scour_number = failure_cases_scour.sum() #for more, https://thispointer.com/count-number-of-true-elements-in-a-numpy-array-in-python/#1
print(failure_cases_scour_number)

100000


In [77]:
no_samples = len(Ed_arch_no_scour) #for more, https://stackoverflow.com/questions/13921647/python-dimension-of-data-frame
print(no_samples)

failure_probability_no_scour = failure_cases_no_scour_number/no_samples
print(failure_probability_no_scour)

failure_probability_scour = failure_cases_scour_number/no_samples
print(failure_probability_scour)

100000
0.0
1.0
